services:
    nginx:
        container_name: "nitrino-nginx"
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./nginx.prod.dockerfile
        ports:
            - 80:80
        environment:
            - NGINX_HOST=local.nitrino.com
            - NGINX_PORT=80
        links:
            - php
        volumes:
            - ./www/storage/app:/var/www/public/storage:ro
            - ./logs:/var/log/nginx

    php:
        container_name: "nitrino-php"
        restart: unless-stopped
        build:
          context: .
          dockerfile: ./php.prod.Dockerfile
        volumes:
          - ./www/storage:/var/www/storage
          - ./www/.env:/var/www/.env
        links:
            - db

    db:
        image: postgres:15.1
        container_name: "nitrino-pgsql"
        restart: unless-stopped
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: "nitrino"
            POSTGRES_USER: "root"
            POSTGRES_PASSWORD: "root"
        volumes:
            - ./pgsql-volume:/var/lib/postgresql/data
